### PR TITLE
update ember-cli

### PR DESCRIPTION
**Pull request by samdemaeyer**
Update ember-cli to 2.13.0

### CODE REVIEW

**Comment by bgentry** [comment]
thanks! :clap:

**Comment by samdemaeyer** [comment]
@bgentry, could you deploy the latest changes please so we can use it ? 😅

**Comment by bgentry** [comment]
released v0.1.0, hopefully that works for you. I made some more progress upgrading the Ember version but didn't get it all the way working (LTS 2.12 tests fail for some reason).

**Comment by samdemaeyer** [comment]
Thanks @bgentry, I did not realise I only upgraded till 2.13 .. 😅 
I have finished the upgrade in [this PR](https://github.com/bgentry/ember-currency/pull/4) https://github.com/bgentry/ember-currency/pull/4 to the latest stable version, all tests pass

**Pull request merged**
